# numpy

* 수학 연산을 위한 Python Package
* numpy array 자료형을 제공
* 수치해석, 통계 관련 기능에서 가장 기본이 되는 Module

In [1]:
import numpy

In [2]:
arr1 = numpy.array([2, 3, 5, 7, 11, 13, 17])
arr1

array([ 2,  3,  5,  7, 11, 13, 17])

In [3]:
type(arr1)
arr1.shape # 7열

(7,)

In [4]:
arr2 = numpy.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
type(arr2)
arr2.shape # 3행4열

(3, 4)

In [6]:
print(arr1.size)
print(arr2.size)

7
12


In [7]:
arr1 = numpy.array([2, 3, 5, 7, 11, 13, 17])
arr1

type(arr1)
arr1.shape # 7열

arr2 = numpy.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr2

type(arr2)
arr2.shape # 3행4열

print(arr1.size)
print(arr2.size)

7
12


## module 별명 짓기

In [8]:
# as [별명] : module의 별명을 [별명]으로

import numpy as np

# 1 ~ 100
arr_100 = np.arange(1, 101)
arr_100

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [9]:
# 1 ~ 100 3의 배수
arr_100_3 = arr_100[arr_100 % 3 == 0]
arr_100_3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

## indexing, slicing

In [10]:
arr_ = np.array([2, 3, 4, 5, 6, 7, 8, 9, 10])
arr2_ = np.array([2, 1, 3])

In [11]:
print(arr_[2])
print(arr_[-3])
print(arr_[[1, 4, -5]])
print(arr_[arr2_])
print(arr_[2:6])
print(arr_[:7])
print(arr_[4:])
print(arr_[2:8:2])

4
8
[3 6 6]
[4 3 5]
[4 5 6 7]
[2 3 4 5 6 7 8]
[ 6  7  8  9 10]
[4 6 8]


## numeric 기본 연산

In [12]:
arr1 = np.arange(10)
arr2 = np.arange(10, 20)

In [13]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
arr1 * 2 # numpy array 내부 모든 값에 * 연산

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
arr1 / 2 # numpy array 내부 모든 값에 / 연산

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [17]:
arr1 + 2 # numpy array 내부 모든 값에 + 연산

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
arr1 - 2 # numpy array 내부 모든 값에 - 연산

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [19]:
arr1 ** 2 # numpy array 내부 모든 값에 ** 연산

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [20]:
arr1 # 저장해주지 않았기에 값이 변하지 않음

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr1 + arr2 # 배열 내 같은 위치에 있는 값끼리 + 연산 (이외 연산도 가능)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

## boolean 연산

In [22]:
arr1 > 4 # arr1 에서 4보다 큰 숫자는 True

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [23]:
arr1 % 2 == 0 # arr1 에서 2로 나눈 나머지가 0일때 True (짝수)

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [24]:
boolean = np.array([True, True, False, True, True, False, True, True, True, False, True])

In [25]:
np.where(boolean) # True가 담긴 index 추출

(array([ 0,  1,  3,  4,  6,  7,  8, 10], dtype=int64),)

In [26]:
np.where(arr1 > 4) # arr1 에서 4보다 큰 숫자 (True)인 index 추출

(array([5, 6, 7, 8, 9], dtype=int64),)

In [27]:
# 200000 이하인 요소만 추출해서 새로운 numpy array로 추출
revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

yen_array = np.array(revenue_in_yen)
bad_days_revenue = yen_array[yen_array <= 200000]
bad_days_revenue # 정답 출력

array([140000, 180000, 170000, 140000, 150000, 110000, 150000, 130000])

In [28]:
# 200000 이하인 요소만 추출해서 새로운 numpy array로 추출 2
revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

yen_array = np.array(revenue_in_yen)
filter = np.where(yen_array <= 200000)
bad_days_revenue = yen_array[filter]
bad_days_revenue # 정답 출력

array([140000, 180000, 170000, 140000, 150000, 110000, 150000, 130000])